package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

// InitConfig creates a sample configuration file at the default location.
//
// This function:
//  1. Creates the config directory if it doesn't exist
//  2. Generates a config file with defaults and helpful comments
//  3. Returns an error if the file already exists (won't overwrite)
//
// Parameters:
//   - force: If true, overwrite existing config file
//
// Returns:
//   - string: Path to the created config file
//   - error: File creation error or file already exists
func InitConfig(force bool) (string, error) {
	configPath := GetDefaultConfigPath()
	configDir := filepath.Dir(configPath)

	// Create config directory if it doesn't exist
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create config directory: %w", err)
	}

	// Check if config already exists
	if !force && DefaultConfigExists() {
		return "", fmt.Errorf("config file already exists at %s (use --force to overwrite)", configPath)
	}

	// Generate sample config
	cfg := GetDefaultConfig()

	// Marshal to YAML with comments
	yamlData, err := generateYAMLWithComments(cfg)
	if err != nil {
		return "", fmt.Errorf("failed to generate YAML: %w", err)
	}

	// Write to file
	if err := os.WriteFile(configPath, []byte(yamlData), 0600); err != nil {
		return "", fmt.Errorf("failed to write config file: %w", err)
	}

	return configPath, nil
}

// yamlSafePath converts a filesystem path to a YAML-safe representation.
// On Windows, backslashes in double-quoted YAML strings are interpreted as
// escape sequences (e.g. \U -> Unicode escape), causing parse errors.
func yamlSafePath(p string) string {
	return filepath.ToSlash(p)
}

// generateJWTSecret generates a cryptographically secure random JWT secret.
// Returns a 32-byte (256-bit) hex-encoded string (64 characters).
func generateJWTSecret() string {
	bytes := make([]byte, 32)
	if _, err := rand.Read(bytes); err != nil {
		// Fallback to a placeholder if crypto/rand fails (extremely unlikely)
		return "REPLACE-ME-WITH-SECURE-SECRET-MIN-32-CHARS"
	}
	return hex.EncodeToString(bytes)
}

// generateYAMLWithComments generates a YAML config file with helpful comments.
func generateYAMLWithComments(cfg *Config) (string, error) {
	yaml := `# DittoFS Configuration File
# This file is automatically generated with default values.
# Modify as needed for your environment.

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARN, ERROR
  level: "` + cfg.Logging.Level + `"
  # Log format: text, json
  format: "` + cfg.Logging.Format + `"
  # Log output: stdout, stderr, or file path
  # When set to a file path, logs are written to the file with rotation enabled.
  # Use "stdout" or "stderr" for console output (rotation is not applied).
  output: "` + yamlSafePath(cfg.Logging.Output) + `"
  # Log rotation settings (only active when output is a file path)
  rotation:
    # Maximum log file size in MB before rotation
    max_size: ` + fmt.Sprint(cfg.Logging.Rotation.MaxSize) + `
    # Maximum number of rotated log files to retain (0 = keep all)
    max_backups: ` + fmt.Sprint(cfg.Logging.Rotation.MaxBackups) + `
    # Maximum number of days to retain old log files (0 = no age limit)
    max_age: ` + fmt.Sprint(cfg.Logging.Rotation.MaxAge) + `
    # Whether to gzip compress rotated log files
    compress: ` + fmt.Sprint(cfg.Logging.Rotation.Compress) + `

# Maximum time to wait for graceful shutdown
shutdown_timeout: ` + cfg.ShutdownTimeout.String() + `

# Control plane database configuration
# Stores users, groups, shares, and permissions
database:
  # Database type: sqlite (single-node) or postgres (HA)
  type: sqlite
  # SQLite configuration (used when type: sqlite)
  sqlite:
    # Path to SQLite database file
    # Default: $XDG_CONFIG_HOME/dittofs/controlplane.db
    path: ""

# Control plane API server configuration (always enabled)
controlplane:
  # Port for control plane HTTP server
  port: 8080
  # Request timeouts
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s
  # JWT authentication configuration
  jwt:
    # JWT signing secret (minimum 32 characters)
    # IMPORTANT: This is auto-generated for development. For production:
    #   1. Generate a secure secret: openssl rand -hex 32
    #   2. Use environment variable: export DITTOFS_CONTROLPLANE_SECRET="your-secret"
    #   3. The environment variable takes precedence over this config value
    secret: "` + generateJWTSecret() + `"
    # Access token lifetime
    access_token_duration: 15m
    # Refresh token lifetime
    refresh_token_duration: 168h  # 7 days

# Cache configuration (WAL-backed, mandatory for crash recovery)
# All writes go through the WAL cache for durability
cache:
  # Directory path for the cache WAL file (required)
  path: "` + yamlSafePath(cfg.Cache.Path) + `"
  # Maximum cache size (supports human-readable formats: "1GB", "512MB", "10Gi")
  size: 1Gi
  # Maximum pending (dirty, not yet uploaded) data size.
  # When exceeded, writes block until the offloader drains data to backend storage.
  # Increase for slow backends (S3) or high write throughput.
  # Default: 2GB
  # max_pending_size: 2Gi

# Background offloader configuration
# Controls how cached data is transferred to the backend block store (S3 or memory).
# These defaults are tuned for good S3 performance out of the box.
offloader:
  # Number of concurrent block uploads to the backend block store
  # Higher values increase throughput for high-latency backends like S3
  # Default: 16
  parallel_uploads: 16
  # Number of concurrent block downloads per file
  # Default: 8
  parallel_downloads: 8
  # Number of blocks to prefetch ahead of sequential reads
  # Default: 16 (64MB lookahead at 4MB block size)
  prefetch_blocks: 16
  # Files smaller than this are flushed synchronously during Flush().
  # Set to 0 to disable (all files use async flush, WAL ensures durability).
  # Default: 0 (disabled)
  small_file_threshold: 0

# Initial admin user configuration
# This is used to bootstrap the first admin user
admin:
  # Admin username
  username: "` + cfg.Admin.Username + `"
  # Admin email (optional)
  email: ""
  # Admin password hash (bcrypt)
  # Set during 'dittofs init --admin' or leave empty for auto-generated password on first start
  # To generate manually: htpasswd -nbB "" "your-password" | cut -d: -f2
  password_hash: ""
`

	return yaml, nil
}

// InitConfigToPath creates a sample configuration file at the specified path.
//
// Similar to InitConfig but allows specifying a custom path.
//
// Parameters:
//   - path: Full path to the config file to create
//   - force: If true, overwrite existing config file
//
// Returns:
//   - error: File creation error or file already exists
func InitConfigToPath(path string, force bool) error {
	configDir := filepath.Dir(path)

	// Create config directory if it doesn't exist
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Check if config already exists
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("config file already exists at %s (use --force to overwrite)", path)
		}
	}

	// Generate sample config with comments
	cfg := GetDefaultConfig()

	// Generate YAML with helpful comments
	yamlData, err := generateYAMLWithComments(cfg)
	if err != nil {
		return fmt.Errorf("failed to generate config: %w", err)
	}

	// Write to file
	if err := os.WriteFile(path, []byte(yamlData), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}
